# Generated by Django 6.0.2 on 2026-03-04 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('year', models.IntegerField(verbose_name='year founded')),
                ('proj_ebitda', models.FloatField(verbose_name='annual project EBITDA')),
                ('company_ebitda', models.FloatField(verbose_name='annual company EBITDA')),
                ('value', models.FloatField()),
                ('risk', models.FloatField()),
                ('date', models.DateTimeField(verbose_name='date uploaded')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('date', models.DateTimeField(verbose_name='date generated')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.company', unique=True)),
            ],
        ),
    ]
