# Generated by Django 6.0.2 on 2026-03-04 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.company'),
        ),
    ]
