# Generated by Django 6.0.2 on 2026-03-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_response_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date',
            field=models.DateField(verbose_name='date uploaded'),
        ),
    ]
