# Generated by Django 6.0.2 on 2026-03-06 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_company_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='date',
        ),
        migrations.AddField(
            model_name='company',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 5, 22, 10, 48, 544701), verbose_name='time uploaded'),
        ),
        migrations.AlterField(
            model_name='response',
            name='date',
            field=models.DateTimeField(verbose_name='time generated'),
        ),
    ]
