# Generated by Django 6.0.2 on 2026-03-07 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_company_date_company_time_alter_response_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 6, 21, 11, 2, 762913), verbose_name='time uploaded'),
        ),
    ]
