# Generated by Django 6.0.2 on 2026-03-07 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_company_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 6, 21, 12, 7, 210414), verbose_name='time uploaded'),
        ),
    ]
