# Generated by Django 6.0.2 on 2026-03-07 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_marketcaps_alter_company_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cik',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='symbol',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 6, 22, 33, 2, 194501), verbose_name='time uploaded'),
        ),
        migrations.AlterField(
            model_name='marketcaps',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
