# Generated by Django 6.0.2 on 2026-03-07 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_company_cik_company_symbol_alter_company_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='time',
            field=models.DateField(default=datetime.date(2026, 3, 6), verbose_name='time uploaded'),
        ),
    ]
